server:
  port: 8101

spring:
  datasource:
    driver-class-name:
    url: jdbc:mysql://rm-2ze79s5qs52l8ol274o.mysql.rds.aliyuncs.com/auth_service?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: coderzzz
    password: coderzzz

  security:
    oauth2:
      client:
        provider:
          my-oauth-provider:
            authorization-uri: https://my-auth-server/oauth/authorize
            jwk-set-uri: https://my-auth-server/token_keys
            token-uri: https://my-auth-server/oauth/token
            user-info-authentication-method: header
            user-info-uri: https://my-auth-server/userinfo
            user-name-attribute: name
        registration:
          my-client-1:
            authorization-grant-type: authorization_code
            client-authentication-method: basic
            client-id: abcd
            client-name: Client for user scope
            client-secret: password
            provider: my-oauth-provider
            redirect-uri: https://my-redirect-uri.com
            scope: user
          my-client-2:
            authorization-grant-type: authorization_code
            client-authentication-method: basic
            client-id: abcd
            client-name: Client for email scope
            client-secret: password
            provider: my-oauth-provider
            redirect-uri: https://my-redirect-uri.com
            scope: email
